version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"  # Exposing only the app to the outside world
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pokerweb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - poker_network  # Ensure both containers are on the same network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1
    restart: always
    ports:
      - "4306:3306"  # Exposing only the app to the outside world
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pokerweb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - poker_network  # Ensure both containers are on the same network
    # Removed the ports section so this container is not exposed to the outside world

networks:
  poker_network:  # Defining a custom network
    driver: bridge