spring:
  application:
    name: PokerBackend
  datasource:
    url: jdbc:mysql://localhost:3306/pokerweb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true