name: Docker Image Build and Push

on:
  push:
    branches:
      - releases  # Trigger the workflow when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (for better multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use GitHub secrets for Docker credentials
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and tag the Docker image using Docker Compose
      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml build

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker-compose -f docker-compose.yml push
